# -*- coding: utf-8 -*-
"""Twitter Stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOhh0cCu8NGO1HYFhMdPePT1pmN2NNTt

# Twitter Stats Notebook
"""

from pandas.io import gbq
import tweepy
import csv
import unicodecsv as csv
import pandas as pd
import datetime

project_id = 'isye-7406'
tw_query = 'select DISTINCT user_id from isye7406.tweet_sentiment'

user_ids = gbq.read_gbq(query=tw_query, dialect ='standard', project_id=project_id)

api_key = 'xGkRGnVcxMNzPtwIeF9DkgHok'
api_secret = '1KqTTuwKflbyuOYD7blPpqYMqhe38yiq2xotOyQpFjGsBiorkB'
token = '127356459-tOgpRDkam66vmlPHMPBlIlpldrwjTsNy7dmTV75H'
token_secret = '6V1ijrv2dYkRx0OsRQZFKYcGbDAJHnYzu8Iiv6HFQMcxt'

auth = tweepy.OAuthHandler(api_key, api_secret)
auth.set_access_token(token, token_secret)
api = tweepy.API(auth)
    
api.wait_on_rate_limit = True

i = 0

l = []
for idx, user_id in user_ids.iterrows():
  #print user_id
  
  try:
    user = api.get_user(user_id[0])
    l.append({'user_id': user.id,
              'name': user.name,
              'screen_name': user.screen_name,
              'follower_count': user.followers_count,
              'listed_count': user.listed_count,
              'statuses_count': user.statuses_count,
              'created_at': user.created_at,
              'location': user.location,
              'time_zone': user.time_zone,
              'lang': user.lang,
              'verified': user.verified,
              'status': 'Active'})
  except tweepy.TweepError as err:

#    print err.args
 #   print type(err.args[0])
  #  print type(err.args[0][0])
   # print err.args[0][0]['message']

    if isinstance(err.args[0][0],dict):
    #	print ('Pass')
	msg = err.args[0][0]['message']
    else:
#	print('fail')
	msg = ''

    print(user_id[0] + ' ' + msg)

    now = datetime.datetime.now()
    
    if 'suspended' in msg:
	code = 'Suspended'
    elif 'not found' in msg:
    	code = 'Not found'
    else:
	code = 'Other'

    l.append({'user_id': 0,
              'name': 'NA',
              'screen_name': user_id[0],
              'follower_count': 0,
              'listed_count': 0,
              'statuses_count': 0,
              'created_at': '1/1/1900',
              'location': 'NA',
              'time_zone': 'NA',
              'lang': 'en',
              'verified': False,
              'status': code})

  #print user.id
  #print user.name
  #print user.screen_name
  #print user.location
  #print user.followers_count
  #print user.listed_count
  #print user.verified
  #print user.statuses_count
  #print user.created_at
  #print user.time_zone
  #print user.lang
  #print user.verified

  i = i + 1
  if (i % 500 == 0):
    print(i)
  
#  if (i >= 10):
 #   break

df = pd.DataFrame(data=l, 
                  columns=['user_id',
                           'name',
                           'screen_name',
                           'follower_count', 
                           'listed_count', 
                           'statuses_count', 
                           'created_at',
                           'location',
                           'time_zone',
                           'lang',
                           'verified',
			   'status'])


df.to_csv(path_or_buf='./twitter_stats.csv', quoting=csv.QUOTE_ALL, header=True, encoding='utf-8')

#print(df)
#user_ids = gbq.to_gbq(df, 'isye7406.twitter_users',project_id, verbose=True,if_exists='replace')

